language: python
python:
  - "2.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsodium-dev
install:
  - (cd linotpd/src && python setup.py install)
  - pip install Pillow
  - pip install codecov freezegun mock nose unittest2
script: (cd linotpd/src && coverage run --source=linotp `which nosetests` --with-pylons=test.ini)
after_success:
  - (cd linotpd/src && codecov)
